// @vitest-environment jsdom
import { act, renderHook, cleanup } from '@testing-library/react';
import { afterEach, it, expect, vi } from 'vitest';
import { ChatProvider } from '../../src/chat/ChatProvider';
import { useChat } from '../../src/chat/useChat';
import { buildRequest } from '../../src/chat/history';
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
const emit = (c: ReadableStreamDefaultController, value: unknown) => c.enqueue(new TextEncoder().encode(JSON.stringify(value) + '\n'));
it('buffers replies, prevents duplicate sends, stops and retries without duplicating the visitor', async () => {
  vi.useFakeTimers(); vi.spyOn(Math, 'random').mockReturnValue(0.5);
  let controller: ReadableStreamDefaultController;
  const fetcher = vi.fn().mockImplementation(() => Promise.resolve(new Response(new ReadableStream({ start(c) { controller = c; } }))));
  vi.stubGlobal('fetch', fetcher);
  const { result } = renderHook(useChat, { wrapper: ChatProvider });
  act(() => { void result.current.send('Hi', 'token'); void result.current.send('duplicate', 'token'); });
  expect(fetcher).toHaveBeenCalledTimes(1);
  await act(async () => { emit(controller, { type: 'delta', text: 'Hello' }); });
  expect(result.current.messages[1].text).toBe('');
  act(() => result.current.stop());
  expect(result.current.messages[1].status).toBe('incomplete');
  act(() => { void result.current.retry('fresh-token'); });
  await act(async () => { emit(controller, { type: 'delta', text: 'Hello again' }); emit(controller, { type: 'done' }); controller.close(); });
  expect(result.current.pending).toBe(true);
  await act(async () => { await vi.advanceTimersByTimeAsync(3999); });
  expect(result.current.messages[1].text).toBe('');
  await act(async () => { await vi.advanceTimersByTimeAsync(1); });
  expect(result.current.pending).toBe(false);
  expect(result.current.messages).toHaveLength(2);
  expect(result.current.messages[1].text).toBe('Hello again');
  expect(result.current.messages[1].status).toBe('complete');
});
it.each(['stop', 'reset'] as const)('cancels a buffered reply during its typing pause on %s', async (action) => {
  vi.useFakeTimers();
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('{"type":"delta","text":"Hidden reply"}\n{"type":"done"}\n')));
  const { result } = renderHook(useChat, { wrapper: ChatProvider });
  await act(async () => { void result.current.send('Hi', 'token'); });
  expect(result.current.messages[1].text).toBe('');
  act(() => result.current[action]());
  await act(async () => { await vi.advanceTimersByTimeAsync(6000); });
  expect(result.current.pending).toBe(false);
  expect(result.current.messages.some(m => m.text === 'Hidden reply')).toBe(false);
  if (action === 'reset') expect(result.current.messages).toEqual([]);
});
it('keeps typing for slow replies and displays the complete result without another delay', async () => {
  vi.useFakeTimers();
  let controller: ReadableStreamDefaultController;
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response(new ReadableStream({ start(c) { controller = c; } }))));
  const { result } = renderHook(useChat, { wrapper: ChatProvider });
  await act(async () => { void result.current.send('Hi', 'token'); emit(controller, { type: 'delta', text: 'Hello' }); await vi.advanceTimersByTimeAsync(6000); });
  expect(result.current.messages[1].text).toBe(''); expect(result.current.pending).toBe(true);
  await act(async () => { emit(controller, { type: 'delta', text: ' there' }); emit(controller, { type: 'done' }); controller.close(); });
  expect(result.current.messages[1].text).toBe('Hello there'); expect(result.current.pending).toBe(false);
});
it('shows errors immediately without displaying an unfinished buffered answer', async () => {
  vi.useFakeTimers();
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('{"type":"delta","text":"Partial"}\n{"type":"error","message":"Please retry."}\n')));
  const { result } = renderHook(useChat, { wrapper: ChatProvider });
  await act(async () => { void result.current.send('Hi', 'token'); });
  expect(result.current.pending).toBe(false);
  expect(result.current.messages[1]).toMatchObject({ text: '', status: 'error', error: 'Please retry.' });
});
it('ignores a late response after reset and retains conversation across hook consumers', async () => {
  let resolve: (r: Response) => void = () => undefined;
  vi.stubGlobal('fetch', vi.fn().mockImplementation(() => new Promise<Response>((r) => { resolve = r; })));
  const { result } = renderHook(useChat, { wrapper: ChatProvider });
  act(() => { void result.current.send('Hi', 'token'); result.current.reset(); });
  await act(async () => { resolve(new Response('{"type":"delta","text":"old"}\n{"type":"done"}\n')); });
  expect(result.current.messages).toEqual([]); expect(result.current.pending).toBe(false);
});
it('does not let an old in-flight response alter a new conversation', async () => {
  const resolvers: Array<(response: Response) => void> = [];
  const fetcher = vi.fn().mockImplementation(() => new Promise<Response>((resolve) => { resolvers.push(resolve); }));
  vi.stubGlobal('fetch', fetcher);
  const { result } = renderHook(useChat, { wrapper: ChatProvider });
  act(() => { void result.current.send('lumang usapan', 'old-token'); });
  const oldSignal = fetcher.mock.calls[0][1].signal as AbortSignal;
  act(() => { result.current.reset(); void result.current.send('Who are you?', 'new-token'); });
  expect(oldSignal.aborted).toBe(true);
  expect(JSON.parse(fetcher.mock.calls[1][1].body).history).toEqual([]);
  await act(async () => { resolvers[0](new Response('{"type":"delta","text":"Lumang sagot"}\n{"type":"done"}\n')); });
  expect(result.current.pending).toBe(true);
  expect(result.current.messages.map(({ text }) => text)).toEqual(['Who are you?', '']);
});
it('bounds UTF-8 history and excludes incomplete exchanges', () => {
  const messages = Array.from({ length: 20 }, (_, i) => ({ id: String(i), role: i % 2 ? 'assistant' as const : 'user' as const, text: 'あ'.repeat(1900), time: '', status: 'complete' as const }));
  const request = buildRequest(messages, 'hello', 'token');
  expect(request.history.length).toBeLessThanOrEqual(12);
  expect(new TextEncoder().encode(JSON.stringify(request)).length).toBeLessThanOrEqual(32768);
  expect(buildRequest([{ ...messages[0] }, { ...messages[1], status: 'incomplete' }], 'hello', 'token').history).toEqual([]);
});
