// @vitest-environment jsdom
import { useEffect, useRef } from 'react';
import { act, render, screen, fireEvent, cleanup, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, it, expect, vi } from 'vitest';
import { ChatProvider } from '../../src/chat/ChatProvider';
import { MessagePanel } from '../../src/components/profile/MessagePanel';
vi.mock('../../src/components/chat/TurnstileChallenge', () => ({ TurnstileChallenge: ({ revision, onToken }: { revision: number; onToken: (t: string) => void }) => {
  const callback = useRef(onToken); callback.current = onToken;
  useEffect(() => callback.current(`token-${revision}`), [revision]);
  return null;
} }));
beforeEach(() => {
  HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  HTMLDialogElement.prototype.close = function () { this.open = false; };
});
afterEach(() => { cleanup(); localStorage.clear(); vi.useRealTimers(); vi.unstubAllGlobals(); });
it('sends empty history after New chat even when the previous conversation was Tagalog', async () => {
  const fetcher = vi.fn().mockImplementation((url) => Promise.resolve(url.endsWith('/config') ? Response.json({ turnstileSiteKey: 'test' }) : new Response('{"type":"delta","text":"Ako ang assistant ni Ronan. OLD_CHAT_MARKER"}\n{"type":"done"}\n')));
  vi.stubGlobal('fetch', fetcher);
  render(<ChatProvider><MessagePanel onClose={vi.fn()} onNavigate={vi.fn()} /></ChatProvider>);
  fireEvent.change(screen.getByLabelText('Message'), { target: { value: 'sino ka? OLD_CHAT_MARKER' } });
  await waitFor(() => expect(screen.getByRole('button', { name: 'Send message' }).hasAttribute('disabled')).toBe(false));
  vi.useFakeTimers();
  await act(async () => fireEvent.click(screen.getByRole('button', { name: 'Send message' })));
  await act(async () => { await vi.advanceTimersByTimeAsync(5000); });
  vi.useRealTimers();
  expect(screen.getByText('Ako ang assistant ni Ronan. OLD_CHAT_MARKER')).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: 'New chat' }));
  expect(screen.queryByText(/OLD_CHAT_MARKER/)).toBeNull();
  fireEvent.change(screen.getByLabelText('Message'), { target: { value: 'Who are you?' } });
  await waitFor(() => expect(screen.getByRole('button', { name: 'Send message' }).hasAttribute('disabled')).toBe(false));
  fireEvent.click(screen.getByRole('button', { name: 'Send message' }));
  const requests = fetcher.mock.calls.filter(([url]) => url === '/api/chat');
  expect(requests).toHaveLength(2);
  expect(JSON.parse(requests[1][1].body)).toEqual({ message: 'Who are you?', history: [], turnstileToken: 'token-2' });
  expect(requests[1][1].body).not.toContain('OLD_CHAT_MARKER');
});
it.each(['Show me a project', 'How did Ronan get started?', 'What does he work with?'])('sends the quick suggestion "%s" directly after verification', async (prompt) => {
  const fetcher = vi.fn().mockImplementation((url) => Promise.resolve(url.endsWith('/config') ? Response.json({ turnstileSiteKey: 'test' }) : new Response('{"type":"delta","text":"Hello"}\n{"type":"done"}\n')));
  vi.stubGlobal('fetch', fetcher);
  render(<ChatProvider><MessagePanel onClose={vi.fn()} onNavigate={vi.fn()} /></ChatProvider>);
  const suggestion = screen.getByRole('button', { name: prompt });
  expect(suggestion.hasAttribute('disabled')).toBe(true);
  await waitFor(() => expect(suggestion.hasAttribute('disabled')).toBe(false));
  fireEvent.click(suggestion);
  expect(fetcher).toHaveBeenCalledTimes(2);
  expect(JSON.parse(fetcher.mock.calls[1][1].body)).toMatchObject({ message: prompt, turnstileToken: 'token-0' });
  expect((screen.getByLabelText('Message') as HTMLTextAreaElement).value).toBe('');
  expect(screen.getByText(prompt)).toBeTruthy();
  expect(screen.getByLabelText("Ronan's assistant is typing")).toBeTruthy();
  expect(screen.queryByRole('button', { name: prompt })).toBeNull();
});
it('keeps typing feedback visible when verification resizes the conversation without pulling readers down', async () => {
  let onResize = () => undefined;
  const disconnect = vi.fn();
  vi.stubGlobal('ResizeObserver', class { constructor(callback: () => void) { onResize = callback; } observe = vi.fn(); disconnect = disconnect; });
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue(Response.json({ turnstileSiteKey: 'test' })));
  const { unmount } = render(<ChatProvider><MessagePanel onClose={() => undefined} onNavigate={() => undefined} /></ChatProvider>);
  await act(async () => undefined);
  const scroller = screen.getByRole('log').parentElement as HTMLDivElement;
  Object.defineProperties(scroller, { scrollHeight: { value: 800, configurable: true }, clientHeight: { value: 300 } });
  act(() => onResize()); expect(scroller.scrollTop).toBe(800);
  scroller.scrollTop = 0; fireEvent.scroll(scroller);
  Object.defineProperty(scroller, 'scrollHeight', { value: 900 });
  act(() => onResize()); expect(scroller.scrollTop).toBe(0);
  unmount(); expect(disconnect).toHaveBeenCalled();
});
it('supports IME, navigation, fresh tokens, close and reopening history', async () => {
  const fetcher = vi.fn().mockImplementation((url) => Promise.resolve(url.endsWith('/config') ? Response.json({ turnstileSiteKey: 'test' }) : new Response('{"type":"delta","text":"[Projects](/#projects)"}\n{"type":"done"}\n')));
  vi.stubGlobal('fetch', fetcher);
  const close = vi.fn(); const navigate = vi.fn();
  const { rerender } = render(<ChatProvider><MessagePanel onClose={close} onNavigate={navigate} /></ChatProvider>);
  expect(screen.getByText(/AI assistant\. Replies can be wrong\./)).toBeTruthy();
  expect(document.body.textContent).not.toMatch(/Google|Gemini|DeepSeek|deepseek-flash/);
  await waitFor(() => expect(screen.getByRole('button', { name: 'Send message' }).hasAttribute('disabled')).toBe(true));
  fireEvent.change(screen.getByLabelText('Message'), { target: { value: 'Hi' } });
  fireEvent.keyDown(screen.getByLabelText('Message'), { key: 'Enter', isComposing: true });
  expect(fetcher).toHaveBeenCalledTimes(1);
  await waitFor(() => expect(screen.getByRole('button', { name: 'Send message' }).hasAttribute('disabled')).toBe(false));
  vi.useFakeTimers();
  await act(async () => fireEvent.keyDown(screen.getByLabelText('Message'), { key: 'Enter' }));
  expect(screen.getByLabelText("Ronan's assistant is typing")).toBeTruthy();
  expect(screen.queryByText('Thinking...')).toBeNull();
  expect(screen.queryByRole('link', { name: 'Projects' })).toBeNull();
  expect(screen.getByRole('button', { name: 'Mute chat sounds' })).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: 'Mute chat sounds' }));
  expect(screen.getByRole('button', { name: 'Unmute chat sounds' })).toBeTruthy();
  await act(async () => { await vi.advanceTimersByTimeAsync(5000); });
  vi.useRealTimers();
  await screen.findByRole('link', { name: 'Projects' });
  fireEvent.click(screen.getByRole('link', { name: 'Projects' })); expect(navigate).toHaveBeenCalledWith('/#projects');
  rerender(<ChatProvider><div>Other page</div></ChatProvider>);
  rerender(<ChatProvider><MessagePanel onClose={close} onNavigate={navigate} /></ChatProvider>);
  expect(screen.getByRole('link', { name: 'Projects' })).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: 'Close messages' })); expect(close).toHaveBeenCalled();
  fireEvent.click(screen.getByRole('button', { name: 'New chat' }));
  expect(screen.queryByRole('link', { name: 'Projects' })).toBeNull();
});
